---
version: 2.1
jobs:
  build:
    machine:
      # https://circleci.com/developer/machine/image/ubuntu-2204
      image: ubuntu-2204:2022.10.2
    steps:
    - checkout
    - run:
        name: build docker image
        command: |
          if [[ -e ~/docker/image.tar ]]; then
            docker load -i ~/docker/image.tar;
          fi
          docker build -t bids/${CIRCLE_PROJECT_REPONAME}:latest .
          mkdir -p ~/docker
          docker save "bids/${CIRCLE_PROJECT_REPONAME}:latest" > ~/docker/image.tar
    - persist_to_workspace:
        root: /home/circleci
        paths:
        - docker/image.tar

  deploy:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
    - attach_workspace:
        at: /tmp/workspace
    - run: docker load -i /tmp/workspace/docker/image.tar
      # DOCKER_PASS and DOCKER_USER are defined as CircleCI env variables (check circleci project in web form)
    - run:
        command: |
          if [[ -n "$DOCKER_PASS" ]]; then
            repo_name=`echo  ${CIRCLE_PROJECT_REPONAME} | tr '[:upper:]' '[:lower:]'`
            echo "${DOCKER_PASS}" | docker login -u ${DOCKER_USER} --password-stdin
            echo "Pushing to DockerHub bids/${repo_name}:unstable"
            docker tag bids/${repo_name} bids/${repo_name}:unstable
            docker push bids/${repo_name}:unstable
            if [[ -n "${CIRCLE_TAG}" ]]; then
              echo "Pushing to DockerHub bids/${repo_name}:${CIRCLE_TAG}"
              docker push bids/${repo_name}:latest
              docker tag bids/${repo_name} bids/${repo_name}:${CIRCLE_TAG}
              docker push bids/${repo_name}:${CIRCLE_TAG};
            fi
          else
            echo "No DOCKER_PASS, skipping push to DockerHub"
          fi

workflows:
  build_deploy:
    jobs:
    - build:
        filters:
          branches:
            only: master
    - deploy:
        requires:
        - build
        filters:
          branches:
            only: master
